[package]
name = "scriptie"
version = "0.1.0"
entrypoint = "scriptie.typ"
authors = ["Kauri P"]
# license = "MIT"
description = "A template for movie scripts."
repository = "https://github.com/KauriP/scriptie"
disciplines = ["film"]
keywords = ["film", "movie", "screenplay", "script", "screenwriting"]
exclude = ["update-typst-packages.nu", "*.pdf"]
